name: port_mobile_app
description: Port Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioningodpre
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.3.1+17

environment:
  sdk: ^3.6.0

dependency_overrides:
  meta: ^1.7.0
  flutter_nfc_kit: ^3.6.0-rc.6
  file_picker: ^10.1.9
    #git:
    #  url: https://github.com/ZeroPass/flutter_nfc_kit.git
  #file_picker:
  #  git:
  #    url: https://github.com/Sameri11/flutter_file_picker.git
  #    ref: fix-issue-1555

dependencies:
  #file_picker: ^10.1.9
  rive: ^0.13.20
  bloc: ^8.1.4
  card_settings:
    git:
      url: https://github.com/ZeroPass/card_settings_zp.git
  dots_indicator: ^3.0.0
  connectivity_plus: ^6.1.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  cupertino_icons: ^1.0.8
  dart_countries_states: ^0.1.1
  date_format: ^2.0.9
  pin_code_fields: ^8.0.1
  port:
    git:
      url: https://github.com/ZeroPass/flutter-port-sdk.git
      #ref: v1.4.0
  equatable: ^2.0.7

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  #flutter_datetime_picker: ^1.5.1
  flutter_holo_date_picker: ^2.0.0
  flutter_platform_widgets: ^7.0.1
  flutter_secure_storage: ^9.2.2
  keyboard_dismisser: ^3.0.0
  flutter_svg: ^1.1.0
  json_serializable: ^6.5.0
  shared_preferences: ^2.2.2
  another_flushbar: ^1.12.30
  logging: ^1.1.0
  flutter_logs: ^2.2.1
  open_file_safe_plus: ^0.0.5
  permission_handler: ^11.3.1
  qr_code_scanner_plus: ^2.0.6
  url_launcher: ^6.2.5
  app_links: ^6.4.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/port-app-Icon-ios.png"
  image_path_android: "assets/images/port_icon.png"
  adaptive_icon_background: "assets/images/port_icon_background.png"
  adaptive_icon_foreground: "assets/images/port_icon_foreground.png"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/anim/checkmarks.riv
    - assets/anim/success_check.flr
    - assets/anim/nfc.flr
    - assets/anim/nfc.riv
    - assets/certs/port_server.cer
    - assets/images/port.png
    - assets/images/port_text.svg
    - assets/images/port_text_white.svg
    - assets/images/port_icon.png
    - assets/images/port_icon_background.png
    - assets/images/port_icon_foreground.png
    - assets/images/port.link.logo.text.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf