name: eosio_passid_mobile_app
description: EOSIO PassID Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  #flutter_nfc_reader:
  #  git:
  #    url: git://github.com/matteocrippa/flutter-nfc-reader.git
  #    ref: master
  bloc: ^4.0.0
  card_settings: ^1.13.0+hotfix.1
  dots_indicator: ^1.2.0
  device_preview: ^0.4.5
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  cupertino_icons: ^0.1.3
  dart_countries_states: ^0.0.8
  date_format: ^1.0.8
  passid:
    path: lib/passid
  dmrtd:
    git:
      url: https://github.com/ZeroPass/dmrtd.git
  equatable: ^1.1.1
  flare_flutter: ^2.0.3
  http: ^0.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  flutter_cupertino_date_picker: ^1.0.24
  flutter_datetime_picker: ^1.3.8
  flutter_holo_date_picker: ^0.1.3+3
  flutter_platform_widgets: ^0.60.1
  flutter_secure_storage: ^3.3.5
  keyboard_dismisser: ^1.0.2
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.17.4
  flutter_tags: ^0.4.8
  json_serializable: ^3.3.0
  cupertino_list_tile: ^0.1.2
  meta: ^1.1.8
  shared_preferences: ^0.5.7+1
  flushbar: ^1.10.4
  eosdart: ^0.4.7
  logging: ^0.11.4
  flutter_logs: ^2.1.1
  f_logs: ^1.2.2
  share: ^0.6.5+4
  flutter_cache_manager: ^2.0.0
  open_file: ^3.0.3
  permission_handler: ^5.0.1+1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/passid_icon.png"
  image_path_android: "assets/images/passid_icon.png"
  adaptive_icon_background: "assets/images/passid_icon_background.png"
  adaptive_icon_foreground: "assets/images/passid_icon_foreground.png"

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/anim/success_check.flr
    - assets/anim/nfc.flr
    - assets/certs/passid_srv.cer
    - assets/images/passid.png
    - assets/images/passid_icon.png
    - assets/images/passid_icon_background.png
    - assets/images/passid_icon_foreground.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf