name: eosio_port_mobile_app
description: Port Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #flutter_nfc_reader:
  #  git:
  #    url: git://github.com/matteocrippa/flutter-nfc-reader.git
  #    ref: master
  bloc: ^7.0.0
  card_settings: ^2.0.3
  dots_indicator: ^2.0.0
  #device_preview: ^0.7.3
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4
  cupertino_icons: ^1.0.2
  dart_countries_states: ^0.1.1
  date_format: ^2.0.2
  port:
    path: lib/port
  dmrtd:
    git:
      url: https://github.com/ZeroPass/dmrtd.git
  equatable: ^2.0.0
  flare_flutter: ^3.0.2
  http: ^0.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_cupertino_date_picker: ^1.0.24
  flutter_datetime_picker: ^1.3.8
  flutter_holo_date_picker: ^0.3.4+1
  flutter_platform_widgets: ^1.2.0
  flutter_secure_storage: ^4.2.0
  keyboard_dismisser: ^2.0.0
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.22.0
  flutter_tags: ^0.4.8
  json_serializable: ^4.1.2
  cupertino_list_tile: ^0.2.0
  meta: ^1.1.8
  shared_preferences: ^2.0.4 #  ^0.5.7+1
  flushbar: ^1.10.4
  eosdart: ^0.4.7 #temporary commented - old sublibraries
  logging: ^1.0.1
  flutter_logs: ^2.1.1
  f_logs: ^2.0.0-alpha-01
  share: ^2.0.1
  flutter_cache_manager: ^3.0.2 #^2.0.0
  open_file: ^3.0.3
  permission_handler: ^6.1.3
  qr_code_scanner: ^0.5.1
  eosdart_ecc: ^0.4.3
  firebase_dynamic_links: ^2.0.7
  rive: ^0.7.22

dependency_overrides:
  convert: ^2.0.1
  crypto: ^2.1.5
  #eosdart_ecc: ^0.4.4
  http: ^0.12.0+4
  json_annotation: ^4.0.0-nullsafety.0
  freezed_annotation: 0.13.0-nullsafety.0
  pointycastle: ^3.1.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/passid_icon.png"
  image_path_android: "assets/images/passid_icon.png"
  adaptive_icon_background: "assets/images/passid_icon_background.png"
  adaptive_icon_foreground: "assets/images/passid_icon_foreground.png"

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/anim/checkmarks.riv
    - assets/anim/success_check.flr
    - assets/anim/nfc.flr
    - assets/anim/nfc.riv
    - assets/certs/port_server.cer
    - assets/images/port.png
    - assets/images/port_text.svg
    - assets/images/port_text_white.svg
    - assets/images/port_icon.png
    - assets/images/port_icon_background.png
    - assets/images/port_icon_foreground.png
    - assets/images/port.link.logo.text.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf